---
title: "Predicting Patient No-Shows"
author: "Joseph O'Malley"
date: "5/1/2018"
output:
  html_document: default
  pdf_document: default
---

#Final Project - Predicting Patient No-Shows


##Data Preparation
```{r}
setwd("~/")
noShow_data_raw <- read.csv("/Users/ultrajosef/Downloads/Macbook 2012 Files/BIA 6301/Final Project/PatientNoShow_data.csv")

require(data.table)
noShow_data <- as.data.table(noShow_data_raw)

###check for NAs
colSums(sapply(noShow_data, is.na))
```

#Exploratory Data Analysis

```{EDA}
########################### EDA ####################################
library(psych)
describe(noShow_data)
names(noShow_data)
##create UniqueID column
noShow_data$UniqID <- seq.int(nrow(noShow_data))

### paste columns and make continuous hours
noShow_data$new_time <- paste(noShow_data$scheduled_hour,noShow_data$am_pm,sep="-")
##recatagorize time
noShow_data$new_time <-
  ifelse(noShow_data$new_time == "3-1", 3,
         ifelse (noShow_data$new_time == "4-1", 4,
                 ifelse(noShow_data$new_time == "5-1", 5,
                        ifelse(noShow_data$new_time == "6-1", 6,
                               ifelse(noShow_data$new_time == "7-1", 7,
                                      ifelse(noShow_data$new_time == "8-1", 8,
                                             ifelse(noShow_data$new_time == "9-1", 9,
                                                    ifelse(noShow_data$new_time == "10-1", 10, 
                                                           ifelse (noShow_data$new_time == "11-1", 11,
                    ifelse(noShow_data$new_time == "12-0", 12,
                        ifelse(noShow_data$new_time == "1-0", 13,
                              ifelse(noShow_data$new_time == "2-0", 14,
                                    ifelse(noShow_data$new_time == "3-0", 15,
ifelse(noShow_data$new_time == "4-0", 16,
  ifelse(noShow_data$new_time == "5-0", 17, 
    ifelse(noShow_data$new_time == "6-0", 18,
      ifelse(noShow_data$new_time == "7-0", 19,
        ifelse(noShow_data$new_time == "8-0", 20,
          ifelse(noShow_data$new_time == "9-0", 21,
            ifelse(noShow_data$new_time == "10-0", 22, 
              ifelse(noShow_data$new_time == "11-0", 23,
                ifelse(noShow_data$new_time == "12-0", 0,
                  ifelse(noShow_data$new_time == "1-1", 1,
                    ifelse(noShow_data$new_time == "2-1", 2, "Unknown"))))))))))))))))))))))))

##check unique counts
noShow_data[, .(number_of_distinct_orders = uniqueN(UniqID)), by = new_time]
noShow_data <- noShow_data[, new_time:=as.numeric(new_time)] 
## look at hist of scheduled times
hist(noShow_data$new_time, main = "Scheduled Appointment Time", axis(side = 1, at = c(0,1,2,3,4,5,6,7,8,9,10,11, 12,13,14,15,16,17,18,19,20,21,22,23,24)))
prop.table(table(noShow_data$new_time))
##look at age
hist(noShow_data$Age, main = "Scheduled Appointment Time")
```

```{r fig.width = 5, fig.height = 6}
##look at days between appointments
boxplot(noShow_data$days_between, main = "Days Between Scheduled appointment and actual",las = 2, pch=16, cex = 1, col = "lightblue",ylab = "Days", border ="black", boxwex = 0.3)
```

```{r echo=T, results='show'}
summary(noShow_data$days_between)
## impute outliers for data below 0 days before appointment as 0
noShow_data$days_between <- ifelse(noShow_data$days_between<0,0, noShow_data$days_between)

##gender
prop.table(table(noShow_data$no_show_y))
prop.table(table(noShow_data$gender))
prop.table(table(noShow_data$new_time))
prop.table(table(noShow_data$am_pm))
prop.table(table(noShow_data$Scholarship))
prop.table(table(noShow_data$Hipertension))
prop.table(table(noShow_data$Diabetes))
prop.table(table(noShow_data$Alcoholism))
prop.table(table(noShow_data$Handcap))
prop.table(table(noShow_data$SMS_received))
```

#Bin Variables

```{Bin Variables}
require(data.table)
##Bin by Age
noShow_data$Age_Binned <- c( "Under16", "16-25", "26-40", "41-60", "61-80", "Over80")[findInterval(noShow_data$Age, c(-Inf, 16, 25, 41, 61, 81, Inf))]
## check numnber of observations in each bin
noShow_data[, .(number_of_distinct_orders = uniqueN(UniqID)), by = Age_Binned]

##Bin by Days Between
## get deciles
quantile(noShow_data$days_between_Binned, probs = seq(0, 1, 0.1), na.rm = FALSE,
         names = TRUE, type = 7)

noShow_data$days_between_Binned <- c( "Under1", "2-7", "7-30", "Over30")[findInterval(noShow_data$days_between, c(-Inf, 1, 7, 30, Inf))]
## check numnber of observations in each bin
noShow_data[, .(number_of_distinct_orders = uniqueN(UniqID)), by = days_between_Binned]

##Bin by Time
noShow_data$new_time_Binned <- c("9p-5am", "Early Morning", "Mid Day", "Evening", "9p-5am")[findInterval(noShow_data$new_time, c(0, 5, 9, 16, 20, 24))]
## check numnber of observations in each bin
noShow_data[, .(number_of_distinct_orders = uniqueN(UniqID)), by = new_time_Binned]

##group handicapped into one
noShow_data$Handicap_Binned <- c(0, 1)[findInterval(noShow_data$Handcap, c(-Inf, 1, Inf))]
## check numnber of observations in each bin
noShow_data[, .(number_of_distinct_orders = uniqueN(UniqID)), by = Handicap_Binned]
```

#A-Rules/Frequent Pattern Analysis

```{A-Rules}

library(Matrix)
library(arules)
library(arulesViz)
###
names(noShow_data)
noShow_data2 <- noShow_data[,c(1:2, 7:10, 12, 15:18)] 
str(noShow_data2)

###convert everything to Factors
noShow_data2 <- noShow_data2[, no_show_y:=as.factor(no_show_y)] 
noShow_data2 <- noShow_data2[, gender:=as.factor(gender)]
noShow_data2 <- noShow_data2[, Scholarship:=as.factor(Scholarship)]
noShow_data2 <- noShow_data2[, Hipertension:=as.factor(Hipertension)] 
noShow_data2 <- noShow_data2[, Diabetes:=as.factor(Diabetes)]
noShow_data2 <- noShow_data2[, Alcoholism:=as.factor(Alcoholism)]
noShow_data2 <- noShow_data2[, SMS_received:=as.factor(SMS_received)]
noShow_data2 <- noShow_data2[, Age_Binned:=as.factor(Age_Binned)]
noShow_data2 <- noShow_data2[, days_between_Binned:=as.factor(days_between_Binned)] 
noShow_data2 <- noShow_data2[, new_time_Binned:=as.factor(new_time_Binned)]
noShow_data2 <- noShow_data2[, Handicap_Binned:=as.factor(Handicap_Binned)]

#transactionize
#create transactions
t_noShow_data <- as(noShow_data2, "transactions")
itemFrequencyPlot(t_noShow_data, topN = 20)


basic_rules <- apriori(t_noShow_data)
print(basic_rules)
inspect(basic_rules[1:10])

basic_rules_sorted <-sort(basic_rules, by = c("lift", "confidence"))
inspect(basic_rules_sorted[1:20])


##explore factors that lead to people missing their appointment
a_rules2 <- apriori(t_noShow_data, parameter = list(support = 0.005, confidence = 0.2, minlen = 2, maxlen = 2), appearance=list(rhs=c("no_show_y=1"))) 

inspect(sort(a_rules2[1:10], by = c("lift", "confidence")))

##explore factors that lead to people making their appointment
a_rules3 <- apriori(t_noShow_data, parameter = list(support = 0.005, confidence = 0.2, minlen = 2, maxlen = 3), 
                    appearance=list(rhs=c("no_show_y=0"))) 

inspect(sort(a_rules3[1:20], by = c("lift", "confidence")))

##check relationship of recieving a text
a_rules4 <- apriori(t_noShow_data, parameter = list(support = 0.005, confidence = 0.2, minlen = 2, maxlen = 3), appearance=list(lhs=c("SMS_received=1"))) 

inspect(sort(a_rules4[1:5], by = c("lift", "confidence")))

a_rules5 <- apriori(t_noShow_data, parameter = list(support = 0.005, confidence = 0.2, minlen = 2, maxlen = 3), appearance=list(rhs=c("SMS_received=1"))) 

inspect(sort(a_rules5[1:10], by = c("lift", "confidence")))
```

#Naive Bayes

```{Naive Bayes}
################################ Niave Bayes #########################
library(e1071)
set.seed(123)

##read in data
noShow_bayes <- noShow_data
names(noShow_bayes)
##subset
noShow_bayes <- noShow_bayes[,c(1:2, 7:10, 12, 15:18)] 
str(noShow_bayes)

###convert everything to Factors
noShow_bayes <- noShow_bayes[, no_show_y:=as.factor(no_show_y)] 
noShow_bayes <- noShow_bayes[, gender:=as.factor(gender)]
noShow_bayes <- noShow_bayes[, Scholarship:=as.factor(Scholarship)]
noShow_bayes <- noShow_bayes[, Hipertension:=as.factor(Hipertension)] 
noShow_bayes <- noShow_bayes[, Diabetes:=as.factor(Diabetes)]
noShow_bayes <- noShow_bayes[, Alcoholism:=as.factor(Alcoholism)]
noShow_bayes <- noShow_bayes[, SMS_received:=as.factor(SMS_received)]
noShow_bayes <- noShow_bayes[, Age_Binned:=as.factor(Age_Binned)]
noShow_bayes <- noShow_bayes[, days_between_Binned:=as.factor(days_between_Binned)] 
noShow_bayes <- noShow_bayes[, new_time_Binned:=as.factor(new_time_Binned)]
noShow_bayes <- noShow_bayes[, Handicap_Binned:=as.factor(Handicap_Binned)]

##rename factors for ease of interpretation
require(data.table)
noShow_bayes$gender <- factor(noShow_bayes$gender, levels = c(0,1), labels = c("F", "M"))
noShow_bayes$Scholarship <- factor(noShow_bayes$Scholarship, levels = c(0,1), labels = c("Yes", "No"))
noShow_bayes$SMS_received <- factor(noShow_bayes$SMS_received, levels = c(0,1), labels = c("No", "Yes"))
noShow_bayes$Handicap_Binned <- factor(noShow_bayes$Handicap_Binned, levels = c(0,1), labels = c("No", "Yes"))
noShow_bayes$no_show_y <- factor(noShow_bayes$no_show_y, levels = c(0,1), labels = c("No", "Yes"))
str(noShow_bayes)

##select sample size
smp_size <- floor(0.85 * nrow(noShow_bayes))

## set the seed to make your partition reproductible
set.seed(123)
train_ind <- sample(seq_len(nrow(noShow_bayes)), size = smp_size)

###split data for training/test sets 
noShow_bayes_train <- noShow_bayes[train_ind,c(1:11)]
noShow_bayes_test <- noShow_bayes[-train_ind,c(1:11)]

#noShow_Tree_train_labels <- noShow_Tree[train_ind, 1]
#noShow_Tree_test_labels <- noShow_Tree[-train_ind,1]

##check proportions of split data to make sure theyre roughly the same
#prop.table(table(noShow_Tree_train_labels$no_show_y)) 
#prop.table(table(noShow_Tree_test_labels$no_show_y))

#train model
noShow_classifier <- naiveBayes(no_show_y ~ ., data = noShow_bayes_train)
noShow_classifier

##looking at non-zeros for reponse rates
noShow_bayes_red <- noShow_bayes[which(noShow_bayes$days_between_Binned == "Under1")] 
prop.table(table(noShow_bayes_red$no_show_y))

noShow_bayes_SMS <- noShow_bayes[which(noShow_bayes$SMS_received == "Yes" | noShow_bayes$days_between_Binned == "7-30")] 
prop.table(table(noShow_bayes_SMS$no_show_y))


##use trained model on test set

noShowPredict <- predict(noShow_classifier, noShow_bayes_test)

NaiveBayes_tabs <- table(noShow_bayes_test$no_show_y,noShowPredict)
NaiveBayes_tabs

Prop_NaiveBayes <- prop.table(NaiveBayes_tabs)
Prop_NaiveBayes

require(caret)
confusionMatrix(NaiveBayes_tabs, positive = "Yes")



#################### Cross Validation/Resampling ########################
require(rpart)
require(caret)
require(klaR)

############## D-Tree (cross-validation) #####################
#simple k-fold cross validation (10-fold)
fitControl <- trainControl(method="cv", number=10) #use fitControl to set options for k-fold cross validation

set.seed(123)
noShow_bayes_10folds <- train(no_show_y~., data=noShow_bayes_train, method="nb", metric="Kappa", trControl=fitControl) #notice we use the train function in caret and pass rpart through it
noShow_bayes_10folds

actual <- noShow_bayes_test$no_show_y
predicted <- predict(noShow_bayes_10folds, noShow_bayes_test, type="raw")
results.matrix <- confusionMatrix(predicted, actual, positive="Yes")
print(results.matrix)
```

#Logistic Regression

```{Logistic Regression}
################### LOGISTIC REGRESSION #################

noShow_glm <- noShow_data[, c(1,2,5:12,14)]

require(DiscriMiner)

### Create Training/Test split
##select sample size
samp_size <- floor(0.85 * nrow(noShow_glm))

## set the seed to make your partition reproductible
set.seed(123)
train_ind2 <- sample(seq_len(nrow(noShow_glm)), size = samp_size)

###split data for training/test sets
noShow_glm_train <- noShow_glm[train_ind2,c(1:11)]
noShow_glm_test <- noShow_glm[-train_ind2,c(1:11)]


###
noShow_Logit <- glm(noShow_glm_train$no_show_y ~. , family= "binomial", data = noShow_glm_train)
options(scipen=999)
summary(noShow_Logit)

##reduce model
noShow_glm_train2 <- noShow_glm_train[,c(1, 3:5, 6:7, 9:10)]
noShow_glm_test2 <- noShow_glm_test[,c(1, 3:5, 6:7, 9:10)]

noShow_Logit2 <- glm(noShow_glm_train2$no_show_y ~. , family= "binomial", data = noShow_glm_train2)

pred_test2 <- predict(noShow_Logit2, noShow_glm_test2)


LOGITS_noShows <- data.frame(predict(noShow_Logit2, noShow_glm_test2))
LOGITS_noShows

ODDS_noShows <- data.frame(exp(LOGITS_noShows))
ODDS_noShows

PROB_noShow <- data.frame(ODDS_noShows/(1+ODDS_noShows))
PROB_noShow

noShow_wODDS <- as.data.frame(c(noShow_glm_test2, PROB_noShow))

##Brute force create confusion matrix from probabilities
noShow_wODDS$ConfusionMatrix <- ifelse(noShow_wODDS[,"no_show_y"] == 1 & noShow_wODDS[,"predict.noShow_Logit2..noShow_glm_test2."]>0.5,"TP",
                  ifelse(noShow_wODDS[,"no_show_y"] == 1 & noShow_wODDS[,"predict.noShow_Logit2..noShow_glm_test2."]<0.5, "FN",
                         ifelse(noShow_wODDS[,"no_show_y"] == 0 & noShow_wODDS[,"predict.noShow_Logit2..noShow_glm_test2."]>0.5, "FP",
                                ifelse(noShow_wODDS[,"no_show_y"] == 0 & test = noShow_wODDS[,"predict.noShow_Logit2..noShow_glm_test2."]<0.5, "TN", "Unknown"))))

prop.table(table(noShow_wODDS$ConfusionMatrix))

#############
```
